name: Gatsby Publish

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: create CNAME file
        run: |
          echo "aclypse" > CNAME
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          GH_PAT: ${{ secrets.GH_PAT }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
